name: Debug FTP Directory Structure

on:
  workflow_dispatch:

jobs:
  debug-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Check FTP Directory
        run: |
          # Install lftp
          sudo apt-get update && sudo apt-get install -y lftp
          
          # Create a debug script
          cat > ftp_debug.sh << 'EOF'
          #!/bin/bash
          echo "=== FTP Directory Debug ==="
          
          lftp -u $FTP_USER,$FTP_PASS ftps://$FTP_SERVER:21 << LFTP_SCRIPT
          set ssl:verify-certificate no
          echo "Current directory after login:"
          pwd
          echo ""
          echo "Directory listing:"
          ls -la
          echo ""
          echo "Checking for public_html:"
          ls -la public_html/
          echo ""
          echo "Checking for domains directory:"
          ls -la domains/
          echo ""
          echo "Full path exploration:"
          find . -type d -name "public_html" 2>/dev/null | head -20
          bye
          LFTP_SCRIPT
          EOF
          
          chmod +x ftp_debug.sh
          
          # Run with OLD Hostinger credentials
          FTP_SERVER="185.212.71.198" \
          FTP_USER="u921052894.SupplySide" \
          FTP_PASS="${{ secrets.FTP_PASSWORD }}" \
          ./ftp_debug.sh