name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "deploy-prod"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite site
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build completed. Checking output..."
          ls -la dist/
          du -sh dist/

      - name: Clean state file
        run: |
          rm -f .ftp-deploy-sync-state.json || true
          rm -f ./dist/.ftp-deploy-sync-state.json || true

      - name: Debug FTP Connection Info
        run: |
          echo "Attempting FTP connection to:"
          echo "Server: ${{ secrets.FTP_SERVER }}"
          echo "Username: ${{ secrets.FTP_USERNAME }}"
          echo "Port: 21"
          echo "Protocol: ftps"
          echo "Target directory: public_html/"

      - name: Deploy to Hostinger via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./dist/
          server-dir: public_html/
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
          dangerous-clean-slate: true
