name: Deploy to Hostinger - Full Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List files to deploy
      run: |
        echo "Files that will be deployed:"
        ls -la
        echo "---"
        echo "HTML files:"
        find . -name "*.html" -type f | grep -v node_modules | grep -v deployment
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        local-dir: ./
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/.env*
          **/deployment/**
          **/backups/**
          **/.DS_Store
          **/Thumbs.db
          **/*.log