name: Matrix Deploy to Multiple Hostinger

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environments to deploy (comma-separated: prod,staging,backup)'
        required: false
        default: 'prod,backup'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod, backup, staging]
      max-parallel: 2  # Deploy to 2 sites at a time
    steps:
      - name: Skip if not selected
        if: github.event_name == 'workflow_dispatch' && !contains(github.event.inputs.environments, matrix.environment)
        run: echo "Skipping ${{ matrix.environment }}"
        
      - name: Download artifacts
        if: github.event_name == 'push' || contains(github.event.inputs.environments, matrix.environment)
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          
      - name: Deploy to ${{ matrix.environment }}
        if: github.event_name == 'push' || contains(github.event.inputs.environments, matrix.environment)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets[format('FTP_SERVER_{0}', matrix.environment)] }}
          username: ${{ secrets[format('FTP_USERNAME_{0}', matrix.environment)] }}
          password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.environment)] }}
          protocol: ftps
          port: 21
          local-dir: ./dist/
          server-dir: ./
          state-name: .ftp-deploy-${{ matrix.environment }}.json